config JWT verification and OIDC header
DataBiosphere/env-base pull request #1
Opened 2020-04-22 14:22 UTC by yonghaoy

With this change, kernel-service-poc would expect a valid jwt token signed by IC. 
And all service can not have oidc in their request header.

Test: curl -I --request POST   --url 'http://34.71.179.202/yyu-kernel-service-poc/api/template/v1/ping?message=foo'   --header 'content-type: ap
plication/json' -H

2020-04-22 15:57 UTC, gmalkov approved these changes

2020-04-22 16:25 UTC, gmalkov requested changes
You need to add these resources to the kustomization manifest or they won't actually be applied. I don't really have much context on this JWT stuff so if you could send me some doc or something that'd be great. I'm mostly just assuming you know what you're doing.

2020-04-23 14:20 UTC, yonghaoy commented
@gmalkov Thanks for your comment! 
https://archive.istio.io/v1.2/docs/ops/security/end-user-auth/ is the related istio topic.
And we did some POC before, and here are some of our findings. Thanks! 
https://docs.google.com/document/d/1cRvtn6JBhz8fqsnKgZGsmsVeZSp_Us-u1kGxpJFWIyk/edit#

2020-04-27 13:53 UTC, gmalkov approved these changes

2020-04-27 18:27 UTC, dvoet commented on config/jwt-checker.yaml
> +        issuer: "https://kernel.integ.envs.broadinstitute.org/"
what is this server?

2020-04-29 14:18 UTC, yonghaoy commented on config/jwt-checker.yaml
> +        issuer: "https://kernel.integ.envs.broadinstitute.org/"
This is our k8s cluster where IC lives: https://kernel.integ.envs.broadinstitute.org/test

2020-05-11 19:30 UTC, dvoet approved these changes

2020-05-11 22:34 UTC, merged